### ISSUE TITLE
Doors not stacking

### ISSUE THREAD

**Issue by MineRealm** [NavidK0/Carbon#130] opened 2014-10-20 01:59 UTC
In Minecraft 1.8, doors should be stackable to 64. Users are currently unable to stack doors in their inventory, using Carbon 1.7.

**Comment by Matmorcat** [comment] 2014-10-20 07:15
I can confirm this is true for only the default oak doors. It only happens while not in creative mode as well. The items appear to stack for a split second and then unstack (the product of the client assuming the doors should stack).

**Comment by NavidK0** [comment] 2014-10-20 19:26
This is because the default doors are not modified by Carbon, therefore, remain the same.

**Comment by starg09** [comment] 2014-10-28 03:42
Could you modify them then? :-P

**Comment by k3ldon** [comment] 2014-10-28 16:23
i think is with essencials

**Comment by NavidK0** [comment] 2014-11-05 07:35
I won't fix this for now, I don't want to break compatibility with other plugins until I can be sure as to why custom doors won't work correctly with LWC.

**Closed as completed by NavidK0** 2014-11-05 07:35 UTC
Labels: issue, wontfix

**Comment by starg09** [comment] 2014-11-05 12:11
Ok, although keep in mind that I don't use lwc, yet I don't seem able to
stack oak or iron doors. I think someone suggested a conflict with
essentials...
